from modules import file_write
import get_names


# fix make stars autogenerated
for file_name in get_names.file_names:
    text = f"""{file_name[:-4]} \n*************************"""
    for formatted_func in (get_names.func_results[file_name[:-4]]):
        text += ("\n" + formatted_func)
    
    file_write.write(file_name, 'a', text)

# section_names = [list(instance.docs[0].keys())[0], list(instance.docs[1].keys())[0]]
# function_names = list(instance.docs[0].values())[0]
# print(function_names)
# api_text = """
# API
# *********

# """
# for name in function_names:
#     api_text += ('.. autofunction:: calculator.' + str(name) + "\n")

# print(api_text)
# write(api_file_name, 'a', api_text)